### ISSUE TITLE
Patterns and constraints in in FHIR Bundle JSON Schema

### ISSUE THREAD

**Issue by jmandel** [microsoft/health-cards-validation-SDK#1]
May be an opportunity with:

* https://github.com/microsoft/health-cards-validation-SDK/blob/06bbb65c4b9afc75082ed1e8a2137209cf0acd66/schema/fhir-bundle-schema.json#L55
* https://github.com/microsoft/health-cards-validation-SDK/blob/06bbb65c4b9afc75082ed1e8a2137209cf0acd66/schema/fhir-bundle-schema.json#L73

... to define some patterns (e.g., "fullUrl should have a colon", or "resourceType should match a know FHIR resource type")

... more broadly this schema pertains to Bundles of Patient resources -- but how does it deal with mixed bundles (e.g., Patient + Immunization resources)?

**Comment by christianpaquin** [comment]
Resolved by #18.
