### ISSUE TITLE
jws-compact validation to return the JWS Payload instead of the JWS Text

### ISSUE THREAD

**Issue by baptistelaget** [microsoft/health-cards-validation-SDK#100]
I'm not sure if this is by design, but the `validate` function from the jws-compact.ts file returns the original `jws: string` argument, instead of the `payload: JWSPayload` that was parsed and validated, making the jws payload visible only in the `log`. 

https://github.com/microsoft/health-cards-validation-SDK/blob/a9743806af315645faf6567ccbbc531b39d033f8/src/jws-compact.ts#L227

Other `return` from this function do return the `payload`, not the original argument, making me think this might be an inconsistency:
https://github.com/microsoft/health-cards-validation-SDK/blob/a9743806af315645faf6567ccbbc531b39d033f8/src/jws-compact.ts#L191

Let me know if this is intended — if not, I can create a pull request for the change.

**Comment by christianpaquin** [comment]
The `result` field is kind of a left over of pre-refactored SDK, we don't really use it anymore in the validation chain. One option would be for us to remove it. If you think there is value (how are you using these return values?), we could keep them; the intent being to return a processed version of the input. For JSON stringified objects, we typically return the parsed JSON. In this case, we wouldn't want to simply return the payload, IMHO, discarding the header and sig.

**Comment by christianpaquin** [comment]
After some discussions, we are proposing removing these parsed returned objects, because we don't make use of them internally; see PR #112.
