### ISSUE TITLE
JWS Schema Validation Error doesn't seem correct

### ISSUE THREAD

**Issue by blingenau** [microsoft/health-cards-validation-SDK#16]
When I try to validate a file of type `jws`, I get the following error:
```
Schema: #/pattern  'should match pattern "^[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+$"'
```
But when I put the regex and the payload into an external regex validator, it passes.

**Comment by christianpaquin** [comment]
Can you possibly share some of data you are using (or create a test `jws` for us to try to repro the behavior?). Could it be an issue with a trailing character?

**Comment by blingenau** [comment]
Good call! I checked the file again and there was a newline at the end, without it it passes validation.

**Comment by christianpaquin** [comment]
It's a bit harsh for the tool to reject the input because of that. I opened issue #17 to accept trailing control char.

**Comment by jmandel** [comment]
I bet you're not the only one who will stumble here though @blingenau  I feel like stripping whitespace around a JWS file might be fair game -- or at least if `strip(input) !== input`, maybe provide a more specific error about whitespace.

**Comment by jmandel** [comment]
(This is especially true since we don't try to standardize a "JWS file" object; it's something that exists purely as a construct for the validator; in real life we create `.smart-health-card` JSON files where lead/trailing whitespace is A-OK as long as the JSON parses.

**Comment by christianpaquin** [comment]
FYI @blingenau , @jmandel; see PR #19.
