### ISSUE TITLE
JWS sig verify fails, but passes in non-SDK verification

### ISSUE THREAD

**Issue by LarrySchoenfeld** [microsoft/health-cards-validation-SDK#28]
Using the SDK to validate our implementation as a Health card JWS signer.    The jws type validation shows the following:
JWS verification failed : (no key found)
Another verifier implementation reports success.

The error is coming from JOSE - but I am having grave difficulty trying to understand what is causing that error to be thrown.  The code in that module is a bit mysterious to me.   The lack of specificity in the error message itself, doesn't help either  - so I am reaching out to you in hopes of a lifeline.   I am guessing you are much more familiar with JOSE than I am.

This is reproducible for any arbitrary JWS which we are generating.

Command line.  node . -t jws -p <PATH> -l debug

The JWKS is read by the well-known API as implemented in your SDK.

FYI --- I also have noted that running 'npm test' results in a significant number of failed tests - not sure if this is a related issue.   I am using the current head of the 'main' branch.  (7b07b9ef7a184b2b7593b8c37661b98123ea0ce5)

The JWS and JWKS is in here
[jwks.zip](https://github.com/microsoft/health-cards-validation-SDK/files/6237600/jwks.zip)

**Comment by christianpaquin** [comment]
@LarrySchoenfeld, we will take a look at the provided examples; thanks for submitting. The SDK is fairly new, so we welcome usability feedback! The error message is indeed cryptic, we have TO-DOs in the code to expand the tests and report finer-grained messages.

Regarding the unit tests failure: they are currently failing due to a [spec change](https://smarthealth.cards/changelog/) (new v0.4.2 spec breaks v0.4.1 currently supported by the SDK). PR #26 fixes that, things will be back to normal when we merge it.

**Comment by christianpaquin** [comment]
A comment after a quick look. The JWT payload is:
```
{"iss":"https://ip1w49nia3.execute-api.us-east-1.amazonaws.com/dev2","iat":1591037940}
```
One issue is that it doesn't contain a FHIR bundle (fatal error). Note also that the `iat` field became `nbf` in [v0.4.2](https://smarthealth.cards/changelog/#042) of the spec. The tool will try to report as much as it can. The validation should continue and the JWT signature should validate. I'll investigate next why it's failing.

**Comment by christianpaquin** [comment]
See [Appendix 3 of RFC7515](https://tools.ietf.org/html/rfc7515#appendix-A.3) for the expected encoding rules.

**Comment by LarrySchoenfeld** [comment]
The signing was done with node crypto package.

Validating the signature with crypto succeeded.

/* Signing snippet */

const signatureBinary = crypto.sign('sha256', Buffer.from(headerBase64Url + '.' + payloadBase64Url), {
  key: keys.privateKey
})
const signatureBase64 = signatureBinary.toString('base64')
const signatureBase64Url = fromBase64(signatureBase64)

return (headerBase64Url + '.' + payloadBase64Url + '.' + signatureBase64Url)

/* Verify snippet */


const signatureBase64 = toBase64(signatureBase64Url)

const signature = Buffer.from(signatureBase64, 'base64')

const isVerified = crypto.verify('sha256', Buffer.from(headerBase64Url + '.' + payloadBase64Url), {
        key: publicKey
    },
    signature)

return isVerified

I'm working on something else --- so I'll take a closer look at this when I have a bit of time.

Your tests use JOSE library to both sign and verify- correct ??
________________________________
From: Christian Paquin ***@***.***>
Sent: Thursday, April 1, 2021 2:32 PM
To: microsoft/health-cards-validation-SDK ***@***.***>
Cc: Schoenfeld, Larry ***@***.***>; Mention ***@***.***>
Subject: (External Email) Re: [microsoft/health-cards-validation-SDK] JWS sig verify fails, but passes in non-SDK verification (#28)

WARNING! This email originated from outside of Change Healthcare.  <https://www.changehealthcare.com/>
Do not click links or open attachments unless you recognize the sender and are expecting the message. Forward this email as an attachment to  ***@***.*** if suspicious.



See Appendix 3 of RFC7515<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftools.ietf.org%2Fhtml%2Frfc7515%23appendix-A.3&data=04%7C01%7Clarry.schoenfeld%40changehealthcare.com%7C1db35ef6abee41fab10108d8f544e9b0%7Cd13a3cbde4ce45e191c298859a236439%7C0%7C0%7C637529023617943451%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EjtUwMjYZ9Oh%2BPWhBIdZjMaNny2%2FCGsy9tq1UIDi3j0%3D&reserved=0> for the expected encoding rules.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fhealth-cards-validation-SDK%2Fissues%2F28%23issuecomment-812124930&data=04%7C01%7Clarry.schoenfeld%40changehealthcare.com%7C1db35ef6abee41fab10108d8f544e9b0%7Cd13a3cbde4ce45e191c298859a236439%7C0%7C0%7C637529023617953410%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ycMLlJ6pQIBVxrOsHmjYYIll7f8H5Wq%2FhXzLF2LF4bM%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATPKGJ7EFFIO3Q2GODDHCI3TGTC5PANCNFSM42E4TB6Q&data=04%7C01%7Clarry.schoenfeld%40changehealthcare.com%7C1db35ef6abee41fab10108d8f544e9b0%7Cd13a3cbde4ce45e191c298859a236439%7C0%7C0%7C637529023617953410%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DHBvgAX2fSr1LJ31w%2FT5C6EbfbbGtUZs1rUFaCPHDVc%3D&reserved=0>.


This message is confidential, intended only for the named recipient(s) and may contain information that is privileged or exempt from disclosure under applicable law. If you are not the intended recipient(s), you are notified that the dissemination, distribution, or copying of this message is strictly prohibited. If you receive this message in error or are not the named recipient(s), please notify the sender by return email and delete this message.

**Comment by christianpaquin** [comment]
@LarrySchoenfeld, try your examples again with the latest commit in the main branch; you'll get extra errors about the signature encoding.
