### ISSUE TITLE
Incorrect(?) SDK Invalidation: SDK assumes all JWKs must conform to SHC rules

### ISSUE THREAD

**Issue by dleve123** [microsoft/health-cards-validation-SDK#33]
## Problem

SHC IG [specifies requirements](https://smarthealth.cards/#determining-keys-associated-with-an-issuer) for public JWK to specify signature validation against (use: sig; alg: ES256, etc). However, the SHC IG does not specify that _all_ public keys hosted a `domain.com/.well-known/jwks.json` must be a SHC-conforming JWK: it's possible that orgs might want to host other various JWKs there and only the JWK with the `kid` matching that in the VC must conform.

## Solution

Update to only validate against the JWK matching the `kid`, not all keys in the key-set

https://github.com/microsoft/health-cards-validation-SDK/blob/fb6a527401e7e49d9bd0433c465ab4bac6498c31/src/shcKeyValidator.ts#L174

cc @jmandel to make sure I'm interpreting the SHC IG correctly

**Comment by dleve123** [comment]
@christianpaquin assuming we are aligned that this is a problem worth solving, I'm happy to help with a patch here.

**Comment by christianpaquin** [comment]
Yes, @dleve123, JWK sets certainly can have more than one key. The tool currently gives warnings for keys that cannot be used for Health Card issuance. The same key validation code runs when you validate a key set directly or when one is downloaded while validating a health card. We chose to be overly verbose, to allow developers to be warned about the contents of their key set (before putting them online), to make sure they don't include something in there by mistake.

What you propose is certainly what a real-life verifier should do. We could be more lenient when validating a health card, not displaying the warnings if one key in the set is ok and can be used with a card, but being a developer tool, it feels like we should report as much as we can.

**Comment by dleve123** [comment]
> What you propose is certainly what a real-life verifier should do. We could be more lenient when validating a health card, not displaying the warnings if one key in the set is ok and can be used with a card, but being a developer tool, it feels like we should report as much as we can.

Gotcha - I appreciate the nuanced thinking between warning and errors! I would learn towards not including warnings due to unrelated keys, but am fine with either decision here. Feel free to close at your discretion.

**Comment by jmandel** [comment]
It might be worth adding a way for developers to explicitly opt out of certain checks (e.g., a suppression file, or a suppression CLI flag). The first time you get a warning, it might come with advice like:

> If you don't want to see this warning in the future you can [...]

While I'm exercising my imagination...the suppression could be scoped to types of errors, or even types of errors combined with data (like, "don't warn me about extra keys" vs "don't warn me about *this* extra key).

(The common version of this is for Node testing frameworks, where you can specify --include or --exclude type flags to filter out the set of tests applied.0

**Comment by christianpaquin** [comment]
> It might be worth adding a way for developers to explicitly opt out of certain checks (e.g., a suppression file, or a suppression CLI flag). The first time you get a warning, it might come with advice like:

Yes, and it should be fairly easy to do since our logger takes in specific error codes which should be easy to filter out.

**Comment by christianpaquin** [comment]
Ok, so I'll close this, and keep @jmandel's suggestion alive on issue #35.
