### ISSUE TITLE
Incorrect SDK Invalidation: SDK doesn't allow `Patient.id`

### ISSUE THREAD

**Issue by dleve123** [microsoft/health-cards-validation-SDK#34]
It seems like the SDK doesn't allow for any FHIR resources to have an `id` attribute:

https://github.com/microsoft/health-cards-validation-SDK/blob/64b4302900a254025f7aab2bcf5dee4a33d2077e/src/fhirBundle.ts#L68

However, this is inconsistent with the [patient FHIR profile](http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/dm-profiles/StructureDefinition-vaccine-credential-patient-dm-definitions.html#Patient.id) and with [the example FHIR payload](http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/dm-profiles/Bundle-Scenario1Bundle.json.html) - which allows for a patient resource to have a (logical) ID.

I'm noticing that [smarthealth.cards examples](https://smarthealth.cards/examples/) never use the (optional) `Patient.id`, so perhaps some data drift between the IG and the FHIR profile is the root of this?

**Comment by christianpaquin** [comment]
FHIR bundle's resource elements shouldn't have an `id` element (among others), as explained in the [health cards are small](https://smarthealth.cards/#health-cards-are-small) section of the spec. The spec examples explicitly [delete](https://github.com/smart-on-fhir/health-cards/blob/7a109d786d26f817fed5f010ee39614f9ffc2132/generate-examples/src/index.ts#L75) these fields from the source bundle.

Makes sense, or are you talking about another `id` element?

**Comment by dleve123** [comment]
Hmm - I see what's stated in the IG, but that language does seem inconsistent with what is in the [FHIR Profiles](http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/dm-profiles/StructureDefinition-vaccine-credential-patient-dm-definitions.html#Patient.id), right?

I believe we want the FHIR profile to be SOT? Or are you suggesting that the FHIR profiles are superseded by the language in the spec?

**Comment by christianpaquin** [comment]
That would be a question for the SMART Health Card spec. Our tool validates conformance to it, as written.

The reason these fields are removed from FHIR bundles is to make sure the signed data can fit into QR codes.

**Comment by jmandel** [comment]
The guidance at http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/dm-profiles/index.html#data-minimization provide expectations here -- `Resource.id` "SHOULD NOT" be included. So it's correct to provide a warning when this is violated.

That said, the language at http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/dm-profiles/StructureDefinition-vaccine-credential-patient-dm-definitions.html#Patient.id is misleading; I'll submit an issue to fix this.  (https://github.com/dvci/vaccine-credential-ig/issues/92)

**Comment by dleve123** [comment]
Closing as this isn't an issue with the validation SDK -- sorry for the false alarm @christianpaquin!

**Comment by christianpaquin** [comment]
No worries. The goal of the SDK is to help developers implement the SMART Health Card spec. Any clarification feedback is very useful!
