### ISSUE TITLE
test failing still?

### ISSUE THREAD

**Issue by LarrySchoenfeld** [microsoft/health-cards-validation-SDK#38]
Refreshed from repo this morning (branch: main,  commit 12f9c690015131ca2f229ffa5a2031dda7b8f8a5) ,  including examples,  and reran tests ( npm test )   numerous test
![Screen Shot 2021-04-05 at 11 13 00 AM](https://user-images.githubusercontent.com/81699623/113596485-fe43fe00-95ff-11eb-8d12-a699c6c275ac.png)
 are still failing.   My expectation  was that tests should now be running clean ?   Please advise.

**Comment by christianpaquin** [comment]
Strange; tests run locally and on the github CI. Could you please share 1) your platform info, and 2) the detailed errors you are seeing?

**Comment by LarrySchoenfeld** [comment]
New secure email message from Change Healthcare

To view the secure message, click on the link below or copy and paste the link into your Internet browser address bar.

https://securemail-changehealthcare.com/s/e?m=ABBwZDrD59YrGOdtfoNEnYYp&c=ABCvr7AIdLbfpmmRwm3lCgGk&em=reply%2bATPKGJ2PEE3W5JWMO5UZLJV6O4TL5EVBNHHDFMKJFI%40reply%2egithub%2ecom

You are reading the plaintext version of this message.  For a better user experience, change your email settings to enable the viewing of HTML.

Do not reply to this notification message; this message was auto-generated by the sender's security system. To reply to the sender, click on the link above.

The secure message expires on Jul 04, 2021 @ 05:48 PM (GMT).

**Comment by christianpaquin** [comment]
I can't access your last message. If you want to provide more info by email, you can send it our project alias: msrhcv@microsoft.com. Thanks!

**Comment by christianpaquin** [comment]
I added macOS tests to our CI on PR #39, tests pass on [latest macOS with node v14](https://github.com/microsoft/health-cards-validation-SDK/pull/39/checks?check_run_id=2271741310). Looked at your error file, seems like the error is with invoking openssl when validating x5c certificate chains. Do you have openssl installed? If so, how do you invoke it from the command line?

**Comment by christianpaquin** [comment]
To have more clarity on the exact error returned for, say, your first failing test, can you replicate it by calling
```
node . -p testdata/valid_key_with_x5c.json -t jwkset -l debug
```
and posting the resulting error?

**Comment by LarrySchoenfeld** [comment]
see attached
________________________________
From: Christian Paquin ***@***.***>
Sent: Monday, April 5, 2021 1:39 PM
To: microsoft/health-cards-validation-SDK ***@***.***>
Cc: Schoenfeld, Larry ***@***.***>; Author ***@***.***>
Subject: (External Email) Re: [microsoft/health-cards-validation-SDK] test failing still? (#38)

WARNING! This email originated from outside of Change Healthcare.  <https://www.changehealthcare.com/>
Do not click links or open attachments unless you recognize the sender and are expecting the message. Forward this email as an attachment to  ***@***.*** if suspicious.



To have more clarity on the exact error returned for, say, your first failing test, can you replicate it by calling

node . -p testdata/valid_key_with_x5c.json -t jwkset -l debug


and posting the resulting error?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fhealth-cards-validation-SDK%2Fissues%2F38%23issuecomment-813566333&data=04%7C01%7Clarry.schoenfeld%40changehealthcare.com%7C4f0ce7dc42fa4531266808d8f8621df5%7Cd13a3cbde4ce45e191c298859a236439%7C0%7C0%7C637532447597710040%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wrsNUgV7Ye358AsDVW1OKgAew8j7IzyIJNOtW4R9%2FEY%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATPKGJ4W5PGNFYL2X5IJKLLTHH7VHANCNFSM42NBS5OA&data=04%7C01%7Clarry.schoenfeld%40changehealthcare.com%7C4f0ce7dc42fa4531266808d8f8621df5%7Cd13a3cbde4ce45e191c298859a236439%7C0%7C0%7C637532447597710040%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8yDwwEgnojJlkNASL%2BpXY4%2B8Ggk9TcPlDeuAM3NiaP4%3D&reserved=0>.


This message is confidential, intended only for the named recipient(s) and may contain information that is privileged or exempt from disclosure under applicable law. If you are not the intended recipient(s), you are notified that the dissemination, distribution, or copying of this message is strictly prohibited. If you receive this message in error or are not the named recipient(s), please notify the sender by return email and delete this message.

**Comment by christianpaquin** [comment]
I don't see the attachment...

**Comment by christianpaquin** [comment]
What version of openssl is installed on your system? You can see by running `openssl version`. Someone else has issues with v1.0.2.

**Comment by LarrySchoenfeld** [comment]
currently at 2.8.3

________________________________
From: Christian Paquin ***@***.***>
Sent: Monday, April 12, 2021 11:42 AM
To: microsoft/health-cards-validation-SDK ***@***.***>
Cc: Schoenfeld, Larry ***@***.***>; Author ***@***.***>
Subject: (External Email) Re: [microsoft/health-cards-validation-SDK] test failing still? (#38)

WARNING! This email originated from outside of Change Healthcare.  <https://www.changehealthcare.com/>
Do not click links or open attachments unless you recognize the sender and are expecting the message. Forward this email as an attachment to  ***@***.*** if suspicious.



What version of openssl is installed on your system? You can see by running openssl version. Someone else has issues with v1.0.2.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fhealth-cards-validation-SDK%2Fissues%2F38%23issuecomment-817960221&data=04%7C01%7Clarry.schoenfeld%40changehealthcare.com%7Ca161fedb9ecc49c9b8f308d8fdd1e62f%7Cd13a3cbde4ce45e191c298859a236439%7C0%7C0%7C637538425240866409%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bisVOHIafKbKN%2FTI0JYPpO4Bi%2FUUDWocfVr%2FyKSnOsY%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATPKGJ2AOBUBA7S3G5DKMF3TIMPFTANCNFSM42NBS5OA&data=04%7C01%7Clarry.schoenfeld%40changehealthcare.com%7Ca161fedb9ecc49c9b8f308d8fdd1e62f%7Cd13a3cbde4ce45e191c298859a236439%7C0%7C0%7C637538425240876369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qaXI%2BjjXr04WuWBpqDUl1Nbg0GAsIqEeIsUyjIKNIg8%3D&reserved=0>.


This message is confidential, intended only for the named recipient(s) and may contain information that is privileged or exempt from disclosure under applicable law. If you are not the intended recipient(s), you are notified that the dissemination, distribution, or copying of this message is strictly prohibited. If you receive this message in error or are not the named recipient(s), please notify the sender by return email and delete this message.

**Comment by LarrySchoenfeld** [comment]
After latest pull late today.

npm test ==>

Test Suites: 3 failed, 1 passed, 4 total
Tests:       34 failed, 75 passed, 109 total

I have told my team that until we can run a clean test suite,  I don't see a lot of value in chasing down issues that come up during validation testing of our implementation.

If I can find some time, I am thinking of jumping in and doing some debugging of the SDK in my environment, cause I am guessing most (if not all) of these issues are environment related.

Thoughts?

________________________________
From: Schoenfeld, Larry ***@***.***>
Sent: Monday, April 12, 2021 1:09 PM
To: microsoft/health-cards-validation-SDK ***@***.***>; microsoft/health-cards-validation-SDK ***@***.***>
Cc: Author ***@***.***>
Subject: Re: (External Email) Re: [microsoft/health-cards-validation-SDK] test failing still? (#38)

currently at 2.8.3

________________________________
From: Christian Paquin ***@***.***>
Sent: Monday, April 12, 2021 11:42 AM
To: microsoft/health-cards-validation-SDK ***@***.***>
Cc: Schoenfeld, Larry ***@***.***>; Author ***@***.***>
Subject: (External Email) Re: [microsoft/health-cards-validation-SDK] test failing still? (#38)

WARNING! This email originated from outside of Change Healthcare.  <https://www.changehealthcare.com/>
Do not click links or open attachments unless you recognize the sender and are expecting the message. Forward this email as an attachment to  ***@***.*** if suspicious.



What version of openssl is installed on your system? You can see by running openssl version. Someone else has issues with v1.0.2.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fhealth-cards-validation-SDK%2Fissues%2F38%23issuecomment-817960221&data=04%7C01%7Clarry.schoenfeld%40changehealthcare.com%7Ca161fedb9ecc49c9b8f308d8fdd1e62f%7Cd13a3cbde4ce45e191c298859a236439%7C0%7C0%7C637538425240866409%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bisVOHIafKbKN%2FTI0JYPpO4Bi%2FUUDWocfVr%2FyKSnOsY%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATPKGJ2AOBUBA7S3G5DKMF3TIMPFTANCNFSM42NBS5OA&data=04%7C01%7Clarry.schoenfeld%40changehealthcare.com%7Ca161fedb9ecc49c9b8f308d8fdd1e62f%7Cd13a3cbde4ce45e191c298859a236439%7C0%7C0%7C637538425240876369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qaXI%2BjjXr04WuWBpqDUl1Nbg0GAsIqEeIsUyjIKNIg8%3D&reserved=0>.


This message is confidential, intended only for the named recipient(s) and may contain information that is privileged or exempt from disclosure under applicable law. If you are not the intended recipient(s), you are notified that the dissemination, distribution, or copying of this message is strictly prohibited. If you receive this message in error or are not the named recipient(s), please notify the sender by return email and delete this message.

**Comment by LarrySchoenfeld** [comment]
One other piece of possibly useful information, --- just scanning thru the errors in the test suite - it looks like the vast majority of the tests that are failing are doing some form of x5c validation.
________________________________
From: Schoenfeld, Larry ***@***.***>
Sent: Monday, April 12, 2021 10:04 PM
To: microsoft/health-cards-validation-SDK ***@***.***>; microsoft/health-cards-validation-SDK ***@***.***>
Cc: Author ***@***.***>
Subject: Re: (External Email) Re: [microsoft/health-cards-validation-SDK] test failing still? (#38)

After latest pull late today.

npm test ==>

Test Suites: 3 failed, 1 passed, 4 total
Tests:       34 failed, 75 passed, 109 total

I have told my team that until we can run a clean test suite,  I don't see a lot of value in chasing down issues that come up during validation testing of our implementation.

If I can find some time, I am thinking of jumping in and doing some debugging of the SDK in my environment, cause I am guessing most (if not all) of these issues are environment related.

Thoughts?

________________________________
From: Schoenfeld, Larry ***@***.***>
Sent: Monday, April 12, 2021 1:09 PM
To: microsoft/health-cards-validation-SDK ***@***.***>; microsoft/health-cards-validation-SDK ***@***.***>
Cc: Author ***@***.***>
Subject: Re: (External Email) Re: [microsoft/health-cards-validation-SDK] test failing still? (#38)

currently at 2.8.3

________________________________
From: Christian Paquin ***@***.***>
Sent: Monday, April 12, 2021 11:42 AM
To: microsoft/health-cards-validation-SDK ***@***.***>
Cc: Schoenfeld, Larry ***@***.***>; Author ***@***.***>
Subject: (External Email) Re: [microsoft/health-cards-validation-SDK] test failing still? (#38)

WARNING! This email originated from outside of Change Healthcare.  <https://www.changehealthcare.com/>
Do not click links or open attachments unless you recognize the sender and are expecting the message. Forward this email as an attachment to  ***@***.*** if suspicious.



What version of openssl is installed on your system? You can see by running openssl version. Someone else has issues with v1.0.2.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fhealth-cards-validation-SDK%2Fissues%2F38%23issuecomment-817960221&data=04%7C01%7Clarry.schoenfeld%40changehealthcare.com%7Ca161fedb9ecc49c9b8f308d8fdd1e62f%7Cd13a3cbde4ce45e191c298859a236439%7C0%7C0%7C637538425240866409%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bisVOHIafKbKN%2FTI0JYPpO4Bi%2FUUDWocfVr%2FyKSnOsY%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATPKGJ2AOBUBA7S3G5DKMF3TIMPFTANCNFSM42NBS5OA&data=04%7C01%7Clarry.schoenfeld%40changehealthcare.com%7Ca161fedb9ecc49c9b8f308d8fdd1e62f%7Cd13a3cbde4ce45e191c298859a236439%7C0%7C0%7C637538425240876369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qaXI%2BjjXr04WuWBpqDUl1Nbg0GAsIqEeIsUyjIKNIg8%3D&reserved=0>.


This message is confidential, intended only for the named recipient(s) and may contain information that is privileged or exempt from disclosure under applicable law. If you are not the intended recipient(s), you are notified that the dissemination, distribution, or copying of this message is strictly prohibited. If you receive this message in error or are not the named recipient(s), please notify the sender by return email and delete this message.

**Comment by christianpaquin** [comment]
Yes indeed, the error is from using openssl to validate x5c chain. Also, I didn't see the attachment you posted above for the results of 
```
node . -p testdata/valid_key_with_x5c.json -t jwkset -l debug
```

**Comment by christianpaquin** [comment]
You can try the new version of the SDK (v.0.4.4) which should ignore openssl failures.
