### ISSUE TITLE
iat => nbf

### ISSUE THREAD

**Issue by blingenau** [microsoft/health-cards-validation-SDK#41]
The spec has changed https://smarthealth.cards/#health-cards-are-encoded-as-compact-serialization-json-web-signatures-jws
nbf should be used in favor of iat, so the schema should be updated accordingly

**Comment by blingenau** [comment]
For those in the internal zulip, here is the conversation where it was brought up https://chat.fhir.org/#narrow/stream/268224-smart.2Finternal-health-cards/topic/nbf.20vs.20iat

**Comment by christianpaquin** [comment]
We switched to expecting `nbf` with version 0.4.2 of the tool (now at v0.4.3). Are you using the latest version? Did we miss an occurrence of `iat` somewhere, if so, can you point where?

**Comment by blingenau** [comment]
Ah, looks like it was because I forgot to build after updating to the latest master 😅 closing
