### ISSUE TITLE
Sometimes .meta is OK after all

### ISSUE THREAD

**Issue by jmandel** [microsoft/health-cards-validation-SDK#43]
We need to update the spec still, but coming soon:

> Bundle.entry[1].resource[Immunization] should not include .meta elements

won't be quite right -- it should be OK for an Immunization `.meta.security[].code` to be populated with one of the allowable IAL values (see http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/#identity-assurance).

**Comment by jmandel** [comment]
https://github.com/smart-on-fhir/health-cards/pull/117 to track the update on the main spec

**Comment by christianpaquin** [comment]
Thanks for the heads up

**Comment by christianpaquin** [comment]
Extra requirement: make the SDK version 0.4.4-1 (with a "pre-release" tag `-1`), this will allow us to start comparing incremental versions of the SDK and let people know of a new update, and not just when the spec/SDK version is bumped.

**Comment by christianpaquin** [comment]
Fixed by #49.
