### ISSUE TITLE
Feature request: Additional "nbf" checks

### ISSUE THREAD

**Issue by jdkizer9** [microsoft/health-cards-validation-SDK#46]
We've seen some health cards issued with `nbf` specifying **milli**seconds since epoch rather than seconds since epoch. Are there any additional checks that we could add to catch these kinds of things? Perhaps checking that `nbf` is the correct order of magnitude that we would expect? Or since `nbf` should be mapping to the issuance date, perhaps checking that `nbf` occurred in the past?

**Comment by christianpaquin** [comment]
Fixed by #48.
