### ISSUE TITLE
Don't fail with openssl 1.0.2

### ISSUE THREAD

**Issue by christianpaquin** [microsoft/health-cards-validation-SDK#47]
Our x5c validation code inadvertently expects openssl v1.1.1. Indeed, the [x509 command](https://www.openssl.org/docs/man1.1.1/man1/x509.html)'s  `-ext` argument is not available on [v1.0.2](https://www.openssl.org/docs/man1.0.2/man1/x509.html).

Either detect the version and skip validation (without failing), or change the validation logic to use openssl features common to both versions.

**Comment by jmandel** [comment]
Might be worth seeing if node's openssl bindings can be used (vs relying on external openssl cli, if these CLI options are less stable over time)

**Comment by christianpaquin** [comment]
> Might be worth seeing if node's openssl bindings can be used (vs relying on external openssl cli, if these CLI options are less stable over time)

What do you mean by node's openssl bindings? Do you mean packages such as [openssl-nodejs](https://www.npmjs.com/package/openssl-nodejs)? If so, I don't think they install openssl, but simply wraps call to it, so we'd have a similar problem.

**Comment by jmandel** [comment]
I just mean that instead of https://github.com/microsoft/health-cards-validation-SDK/blob/main/src/shcKeyValidator.ts#L101-L136, could instead use https://nodejs.org/api/crypto.html#crypto_x509_subjectaltname -- though it looks like this is a recent addition.

**Comment by christianpaquin** [comment]
> I just mean that instead of https://github.com/microsoft/health-cards-validation-SDK/blob/main/src/shcKeyValidator.ts#L101-L136, could instead use https://nodejs.org/api/crypto.html#crypto_x509_subjectaltname -- though it looks like this is a recent addition.

Yes, extracting the subject alt name using node's crypto api would remove the problem with openssl 1.0.2. I also stumbled on the npm [forge](https://www.npmjs.com/package/forge) module which provides javascript [cert chain validation](https://github.com/digitalbazaar/forge/blob/master/lib/x509.js#L2973). Will look into this further...

**Comment by christianpaquin** [comment]
> I also stumbled on the npm [node-forge](https://www.npmjs.com/package/node-forge) module which provides javascript [cert chain validation](https://github.com/digitalbazaar/forge/blob/master/lib/x509.js#L2973). Will look into this further...

I just investigated forge, but it only supports RSA, so we can't use it.

**Comment by christianpaquin** [comment]
> could instead use https://nodejs.org/api/crypto.html#crypto_x509_subjectaltname -- though it looks like this is a recent addition.

The [x509 class](https://nodejs.org/api/crypto.html#crypto_x509_subjectaltname) was added in node v15.6.0. We currently recommend using the LTS (v14) for the SDK, so we should wait before migrating to this method.
