### ISSUE TITLE
Check QR encoding

### ISSUE THREAD

**Issue by jmandel** [microsoft/health-cards-validation-SDK#59]
Related to #56 and #57: ideally would be good to test if the QR encoding follows our recommendations (a segment with byte encoding for `shc:/...` prefix, and a segment with numeric encoding for the JWS that follows). Not sure if this kind of segment-level data is exposed by the underlying libraries, but if *not*, we could use a heuristic like:

1. Decode the QR
2. Re-encode following the recommendations above
3. Check for a  difference QR Version between the symbol we created in (2) and what we got in the beginning

**Comment by christianpaquin** [comment]
[jsQR](https://github.com/cozmo/jsQR/blob/master/dist/jsQR.js) returns the individual chunks, so we'll be able to at least check that.
