### ISSUE TITLE
Allow more than 1 JWS in health card

### ISSUE THREAD

**Issue by kevin-durand** [microsoft/health-cards-validation-SDK#61]
When given a health card with more than 1 verifiable credential JWS string, only the first seems to be validated before exiting.

**Comment by christianpaquin** [comment]
This is indeed a limitation for now. We didn't prioritize this, because most examples and use cases didn't make use of this possibility. Is that something you are planning to use or simply an observation? (useful to know for planning/prioritization purposes...)

**Comment by kevin-durand** [comment]
This is something we're planning on using.

**Comment by christianpaquin** [comment]
The SDK's logging infrastructure would need some non-trivial changes to make this work. To prevent you being blocked while we work on this, you can validate the JWS strings independently (using the `--type jws` option).

Meanwhile, I pushed a commit on the main branch to warn the user about currently non-supported multi-JWS cards.

Also of note, I've opened a [clarification issue](https://github.com/smart-on-fhir/health-cards/issues/132) on the spec.
