### ISSUE TITLE
Wrong algorithm in issuer key

### ISSUE THREAD

**Issue by cpsi-thrive** [microsoft/health-cards-validation-SDK#74]
As reported in https://github.com/microsoft/health-cards-validation-SDK/issues/33 the SDK assumes all JWKs must conform to the SHC rules.  Our first key in .well-known/jwks.json is RS256 and our second key is ES256.

Warning :

- key[rsa-256-v1]: wrong algorithm in issuer key. expected: 'ES256', actual: RS256

Error :

- key[rsa-256-v1]: 'kid' does not match thumbprint in issuer key. expected: p8BIPpITva3PMwvhV-OsFdDDwgYZPqOgEzb24ut4Hjg, actual: rsa-256-v1
- key[rsa-256-v1]: wrong key type in issuer key. expected: 'EC', actual: RSA

I reviewed all the issues related to this and it appears that the solution would be to add an --exclude option to skip this error.

- -e, --exclude <error>      

- error to exclude. Can be repeated. Valid options: "openssl-not-available", "invalid-issuer-url", "invalid-key-x5c" (default: [])

None of the above exclude options apply to this.  

Will there be an additional exclude option added to skip this false positive error?

![qrcode](https://user-images.githubusercontent.com/66029960/116104905-74bfa300-a676-11eb-88cd-b6b79f897a1d.png)

node . -p qrcode.png -t qr

History of issue:
https://github.com/microsoft/health-cards-validation-SDK/issues/33, https://github.com/microsoft/health-cards-validation-SDK/issues/35, https://github.com/microsoft/health-cards-validation-SDK/pull/60

**Comment by christianpaquin** [comment]
PR #76 adds the issuer key exclusion error codes. You'll be able to exclude the ones you want with multiple `-e <code>` parameters, or all in one go with the new wildcard support `-e invalid-key-*`.
