### ISSUE TITLE
Add CORS testing for issuer JWKS

### ISSUE THREAD

**Issue by jmandel** [microsoft/health-cards-validation-SDK#81]
When the HTTP request headers for `GET /.well-known/jwks.json` include `Origin: https://example.org`, the response headers needs to have either:

* `access-control-allow-origin: *`
* `access-control-allow-origin: https://example.org`

**Comment by christianpaquin** [comment]
Can this be enabled on the `https://smarthealth.card
s/examples/issuer/.well-known/jwks.json` end point (since most of the SDK examples use this key set)? Currently,
```
 wget -d --header="Origin: https://example.org" https://smarthealth.cards/examples/issuer/.well-known/jwks.json
```
returns
```
Access-Control-Allow-Origin: *
```

**Comment by jmandel** [comment]
D'oh, I realized I had a copy/paste error in my initial issue post above; fixed to indicate that `*` is an OK response. Basically, the user agent needs to know that its origin is allowed; this is consistent with `*` or with its origin being explicitly included.
