### ISSUE TITLE
Add a "basic profile checks" option (e.g., for data-minimizing COVID-19 US-based issuers)

### ISSUE THREAD

**Issue by jmandel** [microsoft/health-cards-validation-SDK#82]
As our vaccination profiles get more complex, it'll be important to support common use cases with quick/easy verification. I think the starting point here would be a `--profile usa-covid19-immunization` flag that enforces checks like:

* Bundle contains only one Patient and 1..* Immunizations
* Immunizations contain valid CVX codes for COVID-19 immunization products
* FHIR Resources omit fields marked as 0..0 in the DVCI data-minimizing profiles

These checks would be explicitly "less complete" than a full profile validation, but they'd provide helpful feedback and could surface areas where developers are including more data than they mean to, or incorrect data.

The current "Example 0" and "Example 1" in the spec should meet these constraints.

**Comment by christianpaquin** [comment]
Any other profiles to keep on the radar, beyond `usa-covid19-immunization`? There are discussions on zulip for international codes; are these close to ready?

**Comment by jmandel** [comment]
I think we can say that other profiles to keep an eye on are USA-covid19-labs and [specific flavors of international]-covid19-immunizations, but we don't have details to go on yet.

**Comment by ljoy913** [comment]
> * Immunizations contain valid CVX codes for COVID-19 immunization products


Are these the valid codes ? : https://www.cdc.gov/vaccines/programs/iis/COVID-19-related-codes.html

**Comment by jmandel** [comment]
Yes (will note that `211` isn't currently an approved product, but I think it's fine to include from the "current valueset validation" perspective).
