### ISSUE TITLE
OpenSSL possible solution on MAC

### ISSUE THREAD

**Issue by LarrySchoenfeld** [microsoft/health-cards-validation-SDK#87]
Possible resolution for open ssl problem on Mac (???)

Compare attached file to same in  check-cert-san branch.  NOTE:  Attached file is typescript file, but changed suffix to .txt so GIT would accept it as attachment.

[shcKeyValidator.txt](https://github.com/microsoft/health-cards-validation-SDK/files/6461580/shcKeyValidator.txt)

**Comment by christianpaquin** [comment]
So it looks that by cutting the base64-encoded x5c entry into 64-char lines would solve the problem on mac. I'll update the PR so you can give it a fresh start. Thanks for this debugging help.

**Comment by LarrySchoenfeld** [comment]
Yes, apparently the 64 character limit  per line is specified in the standards,  but it is obviously rarely enforced.

________________________________
From: Christian Paquin ***@***.***>
Sent: Wednesday, May 12, 2021 12:59 PM
To: microsoft/health-cards-validation-SDK ***@***.***>
Cc: Schoenfeld, Larry ***@***.***>; Author ***@***.***>
Subject: (External Email) Re: [microsoft/health-cards-validation-SDK] OpenSSL possible solution on MAC (#87)

WARNING! This email originated from outside of Change Healthcare.  <https://www.changehealthcare.com/>
Do not click links or open attachments unless you recognize the sender and are expecting the message. Forward this email as an attachment to  ***@***.*** if suspicious.



So it looks that by cutting the base64-encoded x5c entry into 64-char lines would solve the problem on mac. I'll update the PR so you can give it a fresh start. Thanks for this debugging help.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fhealth-cards-validation-SDK%2Fissues%2F87%23issuecomment-839982654&data=04%7C01%7Clarry.schoenfeld%40changehealthcare.com%7Cab3d14e1aacb432c7a8308d9156fb9e7%7Cd13a3cbde4ce45e191c298859a236439%7C0%7C0%7C637564391866367177%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kT1LS5gXB31Zu9pGw68axxo98g5EWs7U4ESe4cPDjDs%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATPKGJ7V7BILTAFQSGRPDXTTNK6ZBANCNFSM44WVYEJQ&data=04%7C01%7Clarry.schoenfeld%40changehealthcare.com%7Cab3d14e1aacb432c7a8308d9156fb9e7%7Cd13a3cbde4ce45e191c298859a236439%7C0%7C0%7C637564391866377134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qRsf3kx3ALeayLS5wEploE7I8csrfv4N58He7FHzBf8%3D&reserved=0>.


This message is confidential, intended only for the named recipient(s) and may contain information that is privileged or exempt from disclosure under applicable law. If you are not the intended recipient(s), you are notified that the dissemination, distribution, or copying of this message is strictly prohibited. If you receive this message in error or are not the named recipient(s), please notify the sender by return email and delete this message.

**Comment by christianpaquin** [comment]
See updated PR #86, I've integrated your solution. Let me know if it works.

**Comment by christianpaquin** [comment]
I'll close this from now, because it looks like PR #86 fixed the x5c errors. We can open scoped issues for other mac-related problems.
